version: '3.1'

services:

  mongodb:
      container_name: mongodb
      image: mongo:latest
      volumes:
        - myNodeData:/data/db
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=123456
        - MONGO_INITDB_DATABASE=admin

volumes:
  myNodeData: